stages:
- build
- version
- deploy

variables:
  DOCKER_BUILDKIT: 1
  NAS_MOUNT_POINT: /mnt/nas_backup
  BACKUP_DIR: ${NAS_MOUNT_POINT}/container_registry
  VERSION_FILE: VERSION

before_script:
- git config user.email "gitlab-ci@yourdomain.com"
- git config user.name "GitLab CI"

docker-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context "${CI_PROJECT_DIR}/docker" --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:${NEW_IMAGE_TAG}" --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:-latest}" --target tabbyapi-exllamav2-builder-image-runtime
  artifacts:
    reports:
      dotenv: version.env
  rules:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
  - if: '$CI_PIPELINE_SOURCE == "schedule"'
  - if: '$CI_COMMIT_TAG'

increment-version:
  stage: version
  script:
  - NEW_VERSION=$(awk -F. '{$NF = $NF + 1; OFS="."} {print}' $VERSION_FILE)
  - echo $NEW_VERSION > $VERSION_FILE
  - git add $VERSION_FILE
  - git commit -m "Bump version to $NEW_VERSION"
  - git push origin HEAD:$CI_COMMIT_BRANCH
  - git tag v$NEW_VERSION
  - git push origin v$NEW_VERSION
  - echo "NEW_IMAGE_TAG=$NEW_VERSION" >> version.env
  rules:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
  variables:
    GIT_CLEAN_FLAGS: -xffd
  artifacts:
    reports:
      dotenv: version.env

trigger-webhook:
  stage: deploy
  image: curlimages/curl:latest
  script:
  - curl -X POST https://portainer.internal.devguy.dev/api/stacks/webhooks/9d87571d-679f-4bec-ab84-b6457333003c
  rules:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
  - if: '$CI_PIPELINE_SOURCE == "schedule"'
  - if: '$CI_COMMIT_TAG'
  needs:
  - job: docker-build
    artifacts: true
  - job: increment-version
    artifacts: true
