stages:
- test
- build
- deploy

variables:
  DOCKER_BUILDKIT: 1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /kaniko/cache

test:
  stage: test
  script:
    - sudo apt-get install curl
    - curl -X POST https://portainer.rancher.devguy.dev/api/stacks/webhooks/9d87571d-679f-4bec-ab84-b6457333003c

docker-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - mkdir -p /kaniko/cache
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - VERSION="v$(date +%Y.%m.%d).${CI_PIPELINE_IID}"
    - |
      echo "Building Docker image with version: $VERSION"
    - |
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}/docker" \
        --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile" \
        --destination "${CI_REGISTRY_IMAGE}:${VERSION}" \
        --destination "${CI_REGISTRY_IMAGE}:latest" \
        --target tabbyapi-exllamav2-builder-image-runtime \
        --cache-dir /kaniko/cache
  rules:
    - if: '$CI_COMMIT_BRANCH'
      exists:
        - docker/Dockerfile
      changes:
      - docker/**
      - .gitlab-ci.yml


trigger-webhook:
  stage: deploy
  script:
    - curl -X POST https://portainer.rancher.devguy.dev/api/stacks/webhooks/9d87571d-679f-4bec-ab84-b6457333003c
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  needs:
    - job: docker-build
      artifacts: false