stages:
  - build
  - deploy

variables:
  DOCKER_BUILDKIT: 1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /cache/kaniko  # Mount the PVC cache for Kaniko

docker-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script: |
    VERSION="v$(date +%Y.%m.%d).${CI_PIPELINE_IID}"
    echo "Building Docker image with version: $VERSION"
    /kaniko/executor \
        --context "${CI_PROJECT_DIR}/docker" \
        --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile" \
        --destination "${CI_REGISTRY_IMAGE}:${VERSION}" \
        --destination "${CI_REGISTRY_IMAGE}:latest" \
        --target tabbyapi-exllamav2-builder-image-runtime \
        --cache=true \
        --cache-repo="$CI_REGISTRY/$CI_PROJECT_NAMESPACE/cache"  # Cache repo in GitLab registry
        --cache-dir=/kaniko/cache  # Kaniko uses this to cache layers
        --cache-copy-layers \
        --snapshotMode=redo
  rules:
    - if: '$CI_COMMIT_BRANCH'
      exists:
        - docker/Dockerfile
      changes:
        - docker/**
        - .gitlab-ci.yml
