docker-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      if [ -f VERSION ]; then
        CURRENT_VERSION=$(cat VERSION)
      else
        echo "0.0.0" > VERSION
        CURRENT_VERSION="0.0.0"
      fi
      IFS="." read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
      PATCH=$((PATCH + 1))
      NEW_VERSION="$MAJOR.$MINOR.$PATCH"
      echo "$NEW_VERSION" > VERSION
      export IMAGE_TAG="v$NEW_VERSION"
    - | 
      echo "Building Docker image with tag: $IMAGE_TAG"
    - |
      /kaniko/executor --context "${CI_PROJECT_DIR}/docker" \
        --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile" \
        --destination "${CI_REGISTRY_IMAGE}:${IMAGE_TAG}" \
        --destination "${CI_REGISTRY_IMAGE}:latest" \
        --target tabbyapi-exllamav2-builder-image-runtime \
        --cache=true \
        --cache-repo="${CI_REGISTRY_IMAGE}/cache"
  artifacts:
    paths:
      - VERSION
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - docker/Dockerfile
      changes:
        - docker/**
        - .gitlab-ci.yml
